### PR TITLE
Remove loki workaround

### PR DESCRIPTION
**Pull request by nsklikas**
IAM-1229

Upstream problem appears to be fixed by https://github.com/canonical/loki-k8s-operator/pull/453

### CODE REVIEW

**Review by natalian98 — DISMISSED** [review]

**Comment by pik4ez-canonical** [comment]
> It appears that there is no 5.20 lxd release anymore, so the tests are failing. Can we use `latest/stable` instead?
> 
> https://github.com/canonical/openfga-operator/blob/447c799f2c0859915d3eef234d942bfa0365cfa7/.github/workflows/tests.yaml#L36

I understand that setting `latest/stable` will remove some chores from our team. For example, when the release disappears from the upstream like in the mentioned case.

But doesn't it mean that with `latest/stable`, it could be possible for the OpenFGA charm consumers to accidentally get a new major LXD version, which might be non-compatible with the charm?

According to the LXD [docs](https://documentation.ubuntu.com/lxd/en/latest/installing/#choose-your-release), current stable 5.x channels are `5.21/stable` and `5.0/stable` (claimed to be LTS). I would suggest one of these if there are no strong objections.

**Comment by nsklikas** [comment]
> > It appears that there is no 5.20 lxd release anymore, so the tests are failing. Can we use `latest/stable` instead?
> > https://github.com/canonical/openfga-operator/blob/447c799f2c0859915d3eef234d942bfa0365cfa7/.github/workflows/tests.yaml#L36
> 
> I understand that setting `latest/stable` will remove some chores from our team. For example, when the release disappears from the upstream like in the mentioned case.
> 
> But doesn't it mean that with `latest/stable`, it could be possible for the OpenFGA charm consumers to accidentally get a new major LXD version, which might be non-compatible with the charm?
> 
> According to the LXD [docs](https://documentation.ubuntu.com/lxd/en/latest/installing/#choose-your-release), current stable 5.x channels are `5.21/stable` and `5.0/stable` (claimed to be LTS). I would suggest one of these if there are no strong objections.

Agreed, I updated the lxd version. BTW isn't it weird that a release just disappeared or am I stupid?

**Review by BarcoMasile — APPROVED** [review]
Thanks for this

**Comment by pik4ez-canonical** [comment]
> Agreed, I updated the lxd version. BTW isn't it weird that a release just disappeared or am I stupid?

I wouldn't expect something like that to happen. [Asked](https://chat.canonical.com/canonical/pl/u3g4bmx7h7rbjdu8bg348dpr8h) the LXD team for comments.

**Pull request merged**
