### PR TITLE
fix: improve the grafana dashboard

### PR DESCRIPTION
**Pull request by wood-push-melon**
This pull request aims to improve the Grafana dashboard with the following:

- Categorize different visualization graphs into different rows (sections)
- Add more visualizations about traffic, errors, latency, and application
- Improve the details about visualizations (units, descriptions, legends, graphics, etc.)

How to visualize the dashboard:

- Pack & deploy the charm
- Deploy the [`cos` lite bundle](https://charmhub.io/topics/canonical-observability-stack/tutorials/install-microk8s#heading--deploy-the-cos-lite-bundle) and PostgreSQL charm
- Integrate openfga charm with PostgreSQL, grafafa, prometheus, and loki charms

image

### CODE REVIEW

**Comment by BarcoMasile** [comment]
@wood-push-melon can you add some screenshots? So we can view the dashboards without having to go through the deploy and seeding of the data

**Comment by wood-push-melon** [comment]
> @wood-push-melon can you add some screenshots? So we can view the dashboards without having to go through the deploy

Sure. The screenshot is uploaded.

**Review by shipperizer — APPROVED** [review]
i was not able to use the dashboard in the dev environment so i guess best way to try this out is to merge it and verify it

anyway, from what i can tell we could group together some of the graphs as these are a lot of queries to prometheus

probably is always grouping by `grpc_code, grpc_method, grpc_service` when showing the request rates, basically grouping togethere the OK and error codes (more performant from a prometheus perspective compared to separate queries)

anyway imho good to merge

**Review by BarcoMasile — APPROVED** [review]
LGTM, I think Alessandro has a nice proposal on this but also could be a further improvement.
Only one thing to notice: you can see a NaN in the screenshot, please double check that is not an error that stays there even when data flows in. Thanks

**Pull request merged**
